var assert = require("assert");
var request2curl = require("./index");

it("single string url");
it("request.defaults");
describe("Options", function () {
	it("uri || url");
	it("baseUrl");
	it("method");
	it("headers");
	it("qs");
	it("qsParseOptions");
	it("qsStringifyOptions");
	it("useQuerystring");
	it("body");
	it("form");
	it("formData");
	it("multipart");
	it("preampleCRLF");
	it("postambleCRLF");
	it("json");
	it("auth");
	it("oauth");
	it("hawk");
	it("aws");
	it("httpSignature");
	it("followRedirect");
	it("followAllRedirects");
	it("followOriginalHTTPMethod");
	it("maxRedirects");
	it("removeRefererHeader");
	it("encoding");
	it("gzip");
	it("jar");
	it("agent");
	it("agentClass");
	it("agentOptions");
	it("forever");
	it("timeout");
	it("localAddress");
	it("proxy");
	it("strictSSL");
	it("tunnel");
	it("proxyHeaderWhiteList");
	it("proxyHeaderExclusiveList");
	it("time");
	it("har");
});
